### PR TITLE
Format whole document instead of line-by-line

### PR DESCRIPTION
**Pull request by theRoughCode**
This PR implements formatting the whole document instead of line-by-line.
Added a test case for namespaces to show that this multi-line implementation is working.

### CODE REVIEW

**Comment by theRoughCode** [comment]
@amrondonp

**Comment by swernli** [comment]
I'm a little bit confused... I see how the regexp for namespaces was updated to correctly handle multiple lines, but how does the if-statement rule work now? Will it correctly handle multiple if-statements in the file or does that one also need to be updated? It's fine if that is planned for a later update.

**Comment by theRoughCode** [comment]
The tests for the `if` statements still work, but I haven't looked too closely at the cases it covers. cc-ing @amrondonp on this

**Comment by theRoughCode** [comment]
@swernli  I took a look at the code and I think you're right, we have to add `/g` flag at the end to catch multiple.

**Comment by theRoughCode** [comment]
@swernli added a fix for it and a test to catch it

**Pull request merged**
