### PR TITLE
Only check type resolutions for cycles where every callable is type parameterized

### PR DESCRIPTION
**Pull request by bettinaheim**
It would be more efficient to just store whether a node in the call graph has type parameters along with the node.

### CODE REVIEW

**Review by swernli — APPROVED** [review]

**Review by ScottCarda-MS — APPROVED** [review]
This seems like a good improvement for efficiency. Could we wait to merge this in until I can chat with you all tomorrow, and get properly caught up?

**Comment by swernli** [comment]
> This seems like a good improvement for efficiency. Could we wait to merge this in until I can chat with you all tomorrow, and get properly caught up?

Sure thing! Disabled the auto merge so we can sync up tomorrow.

**Comment by ScottCarda-MS** [comment]
@swernli and I had a chat, and I'm all caught up. This looks ready to merge in. Thanks!

**Pull request merged**
