### PR TITLE
Finish implementing the parser visitors for Type in QsFmt

### PR DESCRIPTION
**Pull request by yjt98765**
## Issue
Before this PR, only the `IntType` and `UserDefinedType` defined in [QSharpParser.g4](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Parser/QSharpParser.g4) can be transferred into a syntax tree. The other types are [parsed](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Formatter/ParseTree/Type.fs#L49-L50) into `Unknown` types. This uncompleted implementation prevents formatting rules to be applied within the subtree nodes of a `Type`. For example, the extra spaces inside the brackets are not removed.
```
namespace Foo {
    function Bar () : Int [    ] {}
}
```

## This pull request
In this PR, I have implemented all the other `Type`s defined in [Type.fs](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Formatter/SyntaxTree/Type.fs#L36-L44), i.e., `Missing`, `Parameter`, `Tuple`, `Array`, `Callable`, and `BuiltIn` other than `IntType`. The visitors of their context are created. I also named some ANTLA fields to assist the implementation.

## Testing
After the implementation, the previous example is formatted as
```
namespace Foo {
    function Bar () : Int [ ] {}
}
```
Notice that the extra spaces inside the brackets are removed.

I have added several test cases in [FixedPoints.fs](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Formatter.Tests/FixedPoints.fs) to demonstrate that the types can be parsed without errors. Note that these test cases can **pass** even before the implementation.

### Question
Should I add the code example shown above as a test case? I notice that there is only one example in [Examples.fs](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Formatter.Tests/Examples.fs#L60-L78) to demonstrate that extra spaces are removed. That example serves the same purpose as the one above.

### CODE REVIEW

**Comment by samarsha** [comment]
Thanks. :)

> Should I add the code example shown above as a test case? I notice that there is only one example in [Examples.fs](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Formatter.Tests/Examples.fs#L60-L78) to demonstrate that extra spaces are removed. That example serves the same purpose as the one above.

I think it would make sense to update the tests to include extra whitespace in types. It seems fine to either add them to the existing "Removes extraneous spaces" test (making the example bigger) or adding separate examples for whitespace in types.

**Comment by yjt98765** [comment]
> Thanks. :)
> 
> > Should I add the code example shown above as a test case? I notice that there is only one example in [Examples.fs](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Formatter.Tests/Examples.fs#L60-L78) to demonstrate that extra spaces are removed. That example serves the same purpose as the one above.
> 
> I think it would make sense to update the tests to include extra whitespace in types. It seems fine to either add them to the existing "Removes extraneous spaces" test (making the example bigger) or adding separate examples for whitespace in types.

I chose the first way. This is done with a minor modification in the test.

**Review by samarsha — APPROVED** [review]
Looks great! Thanks for your contribution, this is really helpful. :)

**Pull request merged**
