### PR TITLE
Merge 'main' to 'feature/serialization-deserialization-performance'

### PR DESCRIPTION
**Pull request by cesarzc**
Merge `main` to `feature/serialization-deserialization-performance`.

### CODE REVIEW

**Review by samarsha — APPROVED** [review]

**Comment by bettinaheim** [comment]
@cesarzc I accidentally hit update branch without realizing this PR was not into main when I was respawning the build for PRs to main after reinstating the build.

**Comment by cesarzc** [comment]
> 
> 
> @cesarzc I accidentally hit update branch without realizing this PR was not into main when I was respawning the build for PRs to main after reinstating the build. Sorry.

No problem, it is no longer needed :) I will close it.

**Pull request closed without merging**
